#!/bin/bash

# Creating an ide layout

if [ ! $TMUX ]; then
    echo "Cannot run without being in tmux."
    echo "run command 'tmux'"
else
    if [ "$#" -eq 0 ]; then
        echo "Usage: ide <args>"
        echo 'There are no argument ("ide --list" for list)'
    else
        case $1 in
            "low" | "0")    # Low Level Programming
                tmux rename-window low
                tmux split-window -h
                tmux resize-pane -L 33
                tmux select-pane -t 0
                tmux send-keys -t 0 "export PS1='\[\033[01;32m\] Other Spase: \[\e[0m\]' && clear" C-m
                tmux split-window -v
                tmux resize-pane -U 10
                tmux send-keys -t 1 "export PS1='\[\033[01;36m\]\$ \[\e[0m\]' && clear" C-m
                tmux select-pane -t 1
                tmux select-pane -t 2
                tmux set-option pane-border-format "#[fg=colour0,bg=colour7](#{b:pane_current_path}) #P #(echo $SHELL)"
                tmux send-keys -t 2 "ls" C-m
                ;;
            "high" | "1")   # High Level Programming
                tmux split-window -v
                tmux split-window -h
                tmux resize-pane -D 10
                tmux select-pane -t 0
                tmux send-keys -t 0 "ls" C-m
                clear
                ;;
            "rosd" | "2")   # ros debug
                tmux rename-window ros-debug
                tmux split-window -h
                tmux resize-pane -L 40
                tmux split-window -v
                tmux split-window -h
                tmux select-pane -t 1
                tmux split-window -h
                tmux resize-pane -L 20
                tmux select-pane -t 0
                tmux split-window -v
                tmux resize-pane -U 14
                tmux split-window -v
                tmux select-pane -t 0
                tmux send-keys -t 4 "ls" C-m
                clear
                ;;
            "rose" | "3")   # ros editor
                tmux rename-window ros-editor
                tmux split-window -h
                tmux resize-pane -R 43
                tmux split-window -v
                tmux resize-pane -D 7
                tmux select-pane -t 0
                tmux split-window -v
                tmux resize-pane -D 9
                tmux select-pane -t 0
                tmux send-keys -t 0 "ls" C-m
                clear
                ;;

            "tile" | "4")   # 4-split tiles
                tmux rename-window tile
                tmux split-window -h
                tmux split-window -v
                tmux select-pane -t 0
                tmux split-window -v
                tmux select-pane -t 0
                tmux send-keys -t 0 "ls" C-m
                clear
                ;;
            "-l" | "--list")    # ide script list
                echo -e "\n  Select the command and press Enter."
                echo    "    list:"
                echo    "       0) low"
                echo    "       1) high"
                echo    "       2) rosd"
                echo    "       3) rose"
                echo    "       4) tile"
                echo
                ;;
            *) echo "Invalid argument : $1" ;;
        esac
    fi
fi
