#!/bin/bash

# Creating an ide layout

if [ ! $TMUX ]; then
    echo "Cannot run without being in tmux."
    echo "Run TMUX."
else
    if [ "$#" -eq 0 ]; then
        echo "Usage: ide <args>"
        echo 'There are no argument ("ide --list" for list)'
    else
        case $1 in
            "low" | "0")
                tmux rename-window low
                tmux split-window -h
                tmux resize-pane -L 43
                tmux select-pane -L
                tmux split-window -v
                tmux swap-pane -U
                tmux clock
                tmux resize-pane -U 19
                tmux set-option pane-border-format "#[fg=colour0,bg=colour7](#{b:pane_current_path}) #P #(echo $SHELL)"
                export PS1="\[\033[01;36m\]\$ \[\e[0m\]"
                tmux select-pane -t 1
                tmux select-pane -t 2
                clear
                ;;
            "high" | "1")
                tmux split-window -v
                tmux split-window -h
                tmux resize-pane -D 10
                tmux select-pane -t 1
                clear
                ;;
            "ros" | "2")
                tmux rename-window ros
                tmux split-window -h
                tmux resize-pane -L 4
                tmux select-pane -L
                tmux split-window -v
                tmux resize-pane -U 15
                tmux select-pane -t 0
                clear
                ;;
            "tile" | "3")
                tmux rename-window tile
                tmux split-window -h
                tmux split-window -v
                tmux select-pane -L
                tmux split-window -v
                tmux select-pane -t 0
                clear
                ;;
            "-l" | "--list")
                echo -e "\n  Select the command and press Enter."
                echo    "    list:"
                echo    "       0) low"
                echo    "       1) high"
                echo    "       2) ros"
                echo    "       3) tile"
                echo
                ;;
            *) echo "Invalid argument : $1" ;;
        esac
    fi
fi
